services:
      rpc.server:
            class: Timiki\Bundle\RpcServerBundle\Rps\Handler
            arguments: ['%rpc.server.methods%', '%rpc.server.paths%', '@service_container']
      rpc.proxy:
            class: Timiki\Bundle\RpcServerBundle\Rpc\Proxy
            arguments: ['%rpc.server.proxy%', '@service_container']