language: php

sudo: false

cache:
    directories:
    - $HOME/.composer/cache/files

php:
  - 7.1.3

install:
  - composer install --prefer-dist

script:
  - bin/php-cs-fixer fix --dry-run -v --using-cache=no
  - bin/phpunit